##################################################################
#                   FORMATTING RULES FOR RUSTFMT
##################################################################
# Repo: https://github.com/rust-lang/rustfmt
# See: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=
##################################################################
reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true